name: Build and Tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - master

jobs:
  run-tests:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'

      - name: Install Modules
        run: npm i

      - name: Running Tests
        run: npm run test
