name: Build and Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run-checks:
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
      # Build library
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Install Modules
        run: npm ci

      - name: Build
        run: npm run build

      # Run tests and typecheck
      - name: Typecheck
        run: npm run typecheck

      # - name: Run tests
      #   run: npm run test

      # Build example app
      - name: Install modules
        run: npm ci
        working-directory: ./vue-piwik-pro-example

      - name: Build
        run: npm run build
        working-directory: ./vue-piwik-pro-example
